### ISSUE TITLE
5.4 Comenzamos con el Método ejecutarOpciones

### ISSUE THREAD

**Issue by catastones** [CodeSystem2022/LosChiperos_Cuarto-Semestre#34]
Parte 1 -> listarEstudiantes
Parte 2 -> buscarEstudiantePorId y agregarEstudiante
Parte 3 -> modificarEstudiante
Parte 4 -> eliminarEstudiante y salir

5.5 Ejecutamos y hacemos todas las pruebas

**Comment by gonzalo991** [comment]
Finalizado
